services:
  - type: static_site
    name: red-social-frontend
    env: static
    branch: main
    buildCommand: "npm install && npm run build"
    publishPath: build
    repo: https://github.com/karciss/Frontend_Proyecto_Red_Social.git